"""
Carousel slide designer — full slides rendered by openai/gpt-image-2.

The ENTIRE slide (background, layout, typography, headline and body copy) is
generated by the image model with the text baked in. Nothing is drawn on top
afterwards except the small contact bar (brand name / person / email / mobile),
which is stamped by carousel_composer so those details stay exactly correct.

Public API:
    build_slide_prompt(...) -> str
    generate_slides(slides, brand, ...) -> list[bytes | None]
"""

from __future__ import annotations

import logging
from concurrent.futures import ThreadPoolExecutor

import requests

from tools import image_gen

logger = logging.getLogger(__name__)


def _palette(brand: dict, brand_colors: dict | None) -> str:
    if brand_colors:
        vals = [v for k, v in brand_colors.items()
                if k in ("primary", "secondary", "accent") and isinstance(v, str) and v.startswith("#")]
        if vals:
            return ", ".join(vals)
    return brand.get("brand_colors") or "deep charcoal, warm cream and a single bold accent colour"


def build_slide_prompt(headline: str, body: str, role: str, brand: dict,
                       idx: int, total: int, palette: str,
                       has_photo_ref: bool = False, has_style_ref: bool = False) -> str:
    """
    One design prompt per slide. The model renders the finished slide INCLUDING
    all typography — so the copy must be reproduced verbatim and spelled exactly.
    """
    is_cover = (idx == 0)
    is_last = (idx == total - 1)

    refs = []
    if has_photo_ref:
        refs.append("Use the provided photograph as the real subject of this slide (do not invent a "
                    "different property/product); integrate it into the layout")
    if has_style_ref:
        refs.append("Match the design system of the provided reference slide exactly — same fonts, "
                    "colour palette, spacing and layout language, so the carousel looks like one set")
    ref_block = (" " + ". ".join(refs) + ".") if refs else ""

    if is_cover:
        layout = ("This is the COVER slide: the headline is the dominant element, very large and bold, "
                  "occupying the upper-middle of the frame. Add a small 'SWIPE →' cue at the bottom right.")
    elif is_last:
        layout = ("This is the FINAL slide: a clear conclusion with the headline prominent and the body "
                  "beneath it, plus a strong call-to-action treatment.")
    else:
        layout = (f"This is slide {idx + 1} of {total} ({role}): headline across the top third, body copy "
                  "beneath it in a clean readable block, generous whitespace.")

    body_line = f'Body text (render EXACTLY, verbatim): "{body}"\n' if body.strip() else ""

    return (
        "Design a professional, premium 1:1 square social-media CAROUSEL SLIDE. "
        "Render all typography directly in the image with perfect, crisp, correctly spelled text.\n\n"
        f'Headline (render EXACTLY, verbatim): "{headline}"\n'
        f"{body_line}"
        f"\n{layout}\n\n"
        f"Design system: modern editorial layout, strong typographic hierarchy, high contrast and "
        f"excellent legibility. Colour palette: {palette}. "
        f"Brand: {brand.get('brand_name') or 'the brand'}. "
        "Leave the bottom ~8% of the frame clear and uncluttered for a contact bar.\n"
        "Rules: reproduce the given text word-for-word with correct spelling; no lorem ipsum, no "
        "placeholder text, no watermarks, no spelling errors, no extra invented copy, no logos."
        + ref_block
    )


def _fetch(url: str) -> bytes | None:
    try:
        r = requests.get(url, timeout=60)
        return r.content if r.ok else None
    except Exception:
        return None


def generate_slides(slides: list[dict], brand: dict, palette: str,
                    photo_refs: list[str] | None = None,
                    max_workers: int = 3) -> list[bytes | None]:
    """
    Render every slide with gpt-image-2. The cover is generated first and then
    passed as a STYLE reference to the rest so the whole set looks like one deck.
    `slides`: [{"headline": str, "body": str, "role": str}]
    Returns a list of JPEG/PNG bytes (None where a slide failed).
    """
    total = len(slides)
    photo_refs = photo_refs or []
    out: list[bytes | None] = [None] * total
    if total == 0:
        return out

    def _one(i: int, style_ref: str | None) -> bytes | None:
        s = slides[i]
        photo = photo_refs[i] if i < len(photo_refs) and photo_refs[i] else None
        prompt = build_slide_prompt(
            headline=str(s.get("headline") or "").strip(),
            body=str(s.get("body") or "").strip(),
            role=str(s.get("role") or ""),
            brand=brand, idx=i, total=total, palette=palette,
            has_photo_ref=bool(photo), has_style_ref=bool(style_ref),
        )
        refs = [r for r in (photo, style_ref) if r]
        try:
            gen = image_gen.generate_with_gpt_image(
                prompt, reference_urls=refs or None, aspect_ratio="1:1", quality="high")
            if gen.get("ok") and gen.get("url"):
                return _fetch(gen["url"])
            logger.warning("carousel slide %d failed: %s", i, gen.get("error"))
        except Exception as exc:
            logger.warning("carousel slide %d error: %s", i, exc)
        return None

    # 1) Cover first — it defines the deck's design system.
    out[0] = _one(0, None)

    # Upload the cover so it can be used as a style reference for the rest.
    style_ref_url: str | None = None
    if out[0]:
        try:
            from tools import aws_storage
            up = aws_storage.upload_bytes(out[0], content_type="image/png",
                                          extension="png", folder="carousel_style_ref")
            style_ref_url = up.get("s3_url")
        except Exception as exc:
            logger.warning("carousel: style-ref upload failed: %s", exc)

    # 2) Remaining slides in parallel, all anchored to the cover's style.
    if total > 1:
        with ThreadPoolExecutor(max_workers=max_workers) as ex:
            futures = {ex.submit(_one, i, style_ref_url): i for i in range(1, total)}
            for fut, i in futures.items():
                try:
                    out[i] = fut.result()
                except Exception as exc:
                    logger.warning("carousel slide %d crashed: %s", i, exc)
    return out
